// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/creature": {
            "get": {
                "description": "Lista todas as crituras com filtros opcionais e paginação",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "creatures"
                ],
                "summary": "Lista todas as criaturas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "nome da criatura",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Ataque",
                        "name": "attack",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Defesa",
                        "name": "defence",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Campo de ordenação (name, attack)",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "asc ou desc",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagina",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limite",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma nova criatura",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "creatures"
                ],
                "summary": "Cria uma criatura",
                "parameters": [
                    {
                        "description": "Dados da criatura",
                        "name": "creature",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreatureModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/creature/{id}": {
            "get": {
                "description": "Retorna uma criaturas especifica",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "creatures"
                ],
                "summary": "Busca criatura por ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da criatura",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza dados da criatura",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "creatures"
                ],
                "summary": "Atualiza criatura",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da criatura",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "description": "Dados Atualizados",
                        "name": "creature",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreatureModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta uma criatura do grimorio",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "creatures"
                ],
                "summary": "Deleta criatura",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da criatura",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/creature/{id}/teach/{spellId}": {
            "post": {
                "description": "Associa uma magina a uma Criatura",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "creatures"
                ],
                "summary": "Criatura ensina uma nova magia",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da criatura",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "ID da magia",
                        "name": "spellId",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/spell": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spells"
                ],
                "summary": "Lista magias com filtros",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nome da magia",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "elemento da magia",
                        "name": "element",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "name ou mana_cost",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "asc ou desc",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limite",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma magia",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spells"
                ],
                "summary": "Cria uma nova magia",
                "parameters": [
                    {
                        "description": "Dados da magia",
                        "name": "spell",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SpellModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/spell/element/{element}": {
            "get": {
                "description": "Lista magias por elemento",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spells"
                ],
                "summary": "Lista magias por elemento",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Elemento da magia",
                        "name": "element",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/spell/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spells"
                ],
                "summary": "Busca magias por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da magia",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza dados da magia",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spells"
                ],
                "summary": "Atualiza magias",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da magia",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados Atualizados",
                        "name": "spell",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SpellModel"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deleta magia do grimorio",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spells"
                ],
                "summary": "Deleta magia",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da magia",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreatureModel": {
            "type": "object",
            "properties": {
                "attack": {
                    "type": "integer"
                },
                "defence": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "hp": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "teach_spell": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.SpellModel"
                    }
                }
            }
        },
        "api.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                }
            }
        },
        "api.SpellModel": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "element": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mana_cost": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Grimorio API",
	Description:      "API De Magias e Criaturas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
