// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/spell": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spells"
                ],
                "summary": "Lista magias com filtros",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Elemento da magia",
                        "name": "element",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Nome da magia",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limite",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma magia com nome, descrição, elemento e custo de mana",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spells"
                ],
                "summary": "Cria uma nova magia",
                "parameters": [
                    {
                        "description": "Dados da magia",
                        "name": "spell",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.SpellModel"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                }
            }
        },
        "api.SpellModel": {
            "type": "object",
            "properties": {
                "description_spell": {
                    "type": "string"
                },
                "element": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mana_cost": {
                    "type": "integer"
                },
                "name_spell": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Grimorio API",
	Description:      "API De Magias e Criaturas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
