basePath: /
definitions:
  api.CreatureModel:
    properties:
      attack_creature:
        type: integer
      defence_creature:
        type: integer
      description_creature:
        type: string
      hp_creature:
        type: integer
      id:
        type: string
      name_creature:
        type: string
      teach_spell:
        items:
          $ref: '#/definitions/api.SpellModel'
        type: array
    type: object
  api.Response:
    properties:
      data: {}
      error:
        type: string
    type: object
  api.SpellModel:
    properties:
      description_spell:
        type: string
      element:
        type: string
      id:
        type: string
      mana_cost:
        type: integer
      name_spell:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API De Magias e Criaturas
  title: Grimorio API
  version: "1.0"
paths:
  /api/creature:
    get:
      consumes:
      - application/json
      description: Cria uma magia com nome, descrição, elemento e custo de mana
      parameters:
      - description: Dados da magia
        in: body
        name: spell
        required: true
        schema:
          $ref: '#/definitions/api.SpellModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Cria uma nova magia
      tags:
      - spells
    post:
      consumes:
      - application/json
      description: Criatura ensina uma magia
      parameters:
      - description: id da criatura
        in: query
        name: id
        type: string
      - description: id da magia
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Criatura ensina uma nova magia
      tags:
      - creatures
  /api/creature/{id}:
    delete:
      consumes:
      - application/json
      description: Cria uma magia com nome, descrição, elemento e custo de mana
      parameters:
      - description: Dados da magia
        in: body
        name: spell
        required: true
        schema:
          $ref: '#/definitions/api.SpellModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Cria uma nova magia
      tags:
      - spells
    get:
      consumes:
      - application/json
      description: Cria uma magia com nome, descrição, elemento e custo de mana
      parameters:
      - description: Dados da magia
        in: body
        name: spell
        required: true
        schema:
          $ref: '#/definitions/api.SpellModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Cria uma nova magia
      tags:
      - spells
    put:
      consumes:
      - application/json
      description: Cria uma magia com nome, descrição, elemento e custo de mana
      parameters:
      - description: Dados da magia
        in: body
        name: spell
        required: true
        schema:
          $ref: '#/definitions/api.SpellModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Cria uma nova magia
      tags:
      - spells
  /api/spell:
    get:
      parameters:
      - description: Nome da magia
        in: query
        name: name
        type: string
      - description: elemento da magia
        in: query
        name: element
        type: string
      - description: Página
        in: query
        name: page
        type: integer
      - description: Limite
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
      summary: Lista magias com filtros
      tags:
      - spells
    post:
      consumes:
      - application/json
      description: Cria uma magia com nome, descrição, elemento e custo de mana
      parameters:
      - description: Dados da magia
        in: body
        name: spell
        required: true
        schema:
          $ref: '#/definitions/api.SpellModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Cria uma nova magia
      tags:
      - spells
  /api/spell/{id}:
    delete:
      parameters:
      - description: ID da magia
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
      summary: Deleta magia
      tags:
      - spells
    get:
      parameters:
      - description: ID da magia
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
      summary: Lista magias com filtros por ID
      tags:
      - spells
    put:
      parameters:
      - description: ID da magia
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
      summary: Atualiza magias
      tags:
      - spells
  /api/spell/element/{element}:
    get:
      parameters:
      - description: Elemento da magia
        in: query
        name: element
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
      summary: Lista magias por elemento
      tags:
      - spells
swagger: "2.0"
